spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2-console

  web:
    locale: es
    encoding:
      charset: UTF-8
      enabled: true

  webflux:
    static-path-pattern: /swagger-ui/**

logging:
  level:
    root: warn
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.boot: DEBUG
    com.bci.smart: DEBUG
    org.hibernate.SQL: debug

jwt:
  secret: Q2hC+GvzK3oB9Nn5S5XId6VJbhvH3KJ4FhRqK7/lTlc=
  expiration: 86400

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/